name: ucar_test_task

services:
  ucar_db:
    image: postgres:17
    container_name: ucar_db
    env_file:
      - path: ./src/.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./src/db/db_init:/docker-entrypoint-initdb.d/
      - ./volumes/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./src/.env
    container_name: ucar_backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - ${APP_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      ucar_db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Applying database migrations...' &&
        poetry run alembic upgrade head &&
        echo 'Starting application...' &&
        poetry run python -m main
      "
    networks:
      - net

networks:
  net:
    driver: bridge